/* MBook — Copyright (C) 2026 rupsdbb
   SPDX-License-Identifier: GPL-3.0-or-later */
'use strict';

/* =====================================================================
   Export: PDF, Excel (.xlsx) and a plain HTML page — all built here, so
   the tool keeps working offline with no libraries.
   ===================================================================== */

// Measurement sheet as display rows (shared by all three formats)
function sheetRows() {
  return project.lines.map((l, i) => {
    const c = compute(l);
    const dims = DIMS.map(d => {
      const r = evalExpr(l[d]);
      return r.error ? l[d] : r.value === null ? '' : fmtDim(r.value, c.uf);
    });
    return {
      n: i + 1, line: l, c, code: l.code,
      short: c.info ? c.info.short : (l.code ? 'Not in SOR' : ''),
      desc: l.desc, dims, hdSection: l.hdSection,
      qty: l.code || c.qty ? fmtQty(c.qty, c.uf) : '',
      unit: c.info?.unit || l.ref?.unit || '',
      price: c.sor ? fmtMoney(c.price) : (c.look ? '—' : ''),
      amount: c.sor ? fmtMoney(c.amount) : '',
      po: l.poItem, asset: l.asset,
    };
  });
}
const sheetTotal = () => roundTo(project.lines.reduce((t, l) => t + compute(l).amount, 0), 2);

// Report as a flat list of rows: group headings, items, measurement lines,
// subtotals and the grand total
function reportRows(levels, hideZero, detail) {
  const root = buildReport(levels), rows = [];
  function items(node, path) {
    let sl = 0;
    for (const it of visibleItems(node, hideZero)) {
      rows.push({ type: 'item', sl: ++sl, it, path });
      if (detail) for (const ln of it.lines) rows.push({ type: 'detail', it, ln });
    }
  }
  function group(node, depth, path) {
    for (const kid of node.kids.values()) {
      if (!hasVisible(kid, hideZero)) continue;
      const p = [...path, kid.name];
      rows.push({ type: 'group', depth, label: FIELD_LABEL[kid.field], name: kid.name });
      if (kid.kids.size) group(kid, depth + 1, p); else items(kid, p);
      rows.push({ type: 'subtotal', depth, name: kid.name, amount: kid.amount });
    }
  }
  if (levels.length) group(root, 0, []); else items(root, []);
  rows.push({ type: 'grand', amount: root.amount });
  return rows;
}
function itemText(it) {
  const noRate = it.look && !it.sor;
  return {
    short: it.info ? it.info.short : 'Not in SOR',
    unit: it.info?.unit || '',
    qty: it.err ? '#ERR' : fmtQty(it.qty, it.uf),
    price: noRate ? '—' : it.sor ? fmtMoney(it.price) : '',
    amount: it.sor ? fmtMoney(it.amount) : '',
  };
}
const groupingName = levels => levels.map(f => FIELD_LABEL[f]).join(' › ') || 'Service No (abstract)';
function exportMeta() {
  return [
    project.state ? `State: ${project.state}` : '',
    project.date ? `Rates as on ${fmtDate(project.date)}` : 'No rate date set',
    discountFrac() ? `Discount ${project.discount}%` : '',
    `SOR: ${SOR.source}`,
    `Generated by ${APP_ID} on ${new Date().toLocaleDateString('en-GB').replace(/\//g, '-')}`,
  ].filter(Boolean);
}

/* ---------- dialog ---------- */
$('btnExport').onclick = () => {
  $('xGroup').innerHTML = $('repGroup').innerHTML;
  $('xGroup').value = $('repGroup').value;
  $('xHideZero').checked = $('repHideZero').checked;
  $('xDetail').checked = $('repDetail').checked;
  $('xSheet').checked = $('xReport').checked = true;
  $('dlgExport').returnValue = '';
  $('dlgExport').showModal();
};
$('dlgExport').addEventListener('close', () => {
  if ($('dlgExport').returnValue !== 'ok') return;
  const opts = {
    fmt: document.querySelector('input[name="xfmt"]:checked').value,
    sheet: $('xSheet').checked, report: $('xReport').checked,
    levels: reportLevels($('xGroup')),
    hideZero: $('xHideZero').checked, detail: $('xDetail').checked,
  };
  if (!opts.sheet && !opts.report) return toast('Nothing chosen to export');
  if (!project.lines.length) return toast('The sheet is empty');
  const base = safeName(project.name || 'BOQ');
  try {
    if (opts.fmt === 'pdf') downloadBlob(`${base}.pdf`, exportPdf(opts));
    else if (opts.fmt === 'xlsx') downloadBlob(`${base}.xlsx`, exportXlsx(opts));
    else download(`${base}.html`, exportHtml(opts), 'text/html');
    toast(`Exported ${base}.${opts.fmt}`);
  } catch (err) {
    console.error(err);
    alert(`Export failed: ${err.message}`);
  }
});
function downloadBlob(name, blob) {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = name;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
}

/* ---------- plain HTML (no scripts) ---------- */
function exportHtml(o) {
  const title = project.name || 'BOQ';
  let body = `<h1>${esc(title)}</h1><p class="meta">${exportMeta().map(esc).join(' · ')}</p>`;
  if (o.sheet) {
    body += '<h2>Measurement sheet</h2><div class="wrap"><table><thead><tr><th class="num">#</th><th>Service No</th><th>Short Text</th>' +
      '<th>Description</th><th class="num">No</th><th class="num">L</th><th class="num">B</th><th class="num">H/D</th>' +
      '<th class="num">Qty</th><th>Unit</th><th class="num">Price</th><th class="num">Amount</th><th>PO Item</th><th>Asset</th></tr></thead><tbody>';
    for (const r of sheetRows()) {
      body += `<tr><td class="num">${r.n}</td><td>${esc(r.code)}</td><td>${esc(r.short)}</td><td>${esc(r.desc)}</td>` +
        r.dims.map((d, i) => `<td class="num">${esc(d)}${i === 3 && r.hdSection ? `<div class="sec">${esc(r.hdSection)}</div>` : ''}</td>`).join('') +
        `<td class="num">${esc(r.qty)}</td><td>${esc(r.unit)}</td><td class="num">${esc(r.price)}</td>` +
        `<td class="num">${esc(r.amount)}</td><td>${esc(r.po)}</td><td>${esc(r.asset)}</td></tr>`;
    }
    body += `</tbody><tfoot><tr><td colspan="11" class="num">Total</td><td class="num">${fmtMoney(sheetTotal())}</td><td colspan="2"></td></tr></tfoot></table></div>`;
  }
  if (o.report) {
    body += `<h2>Report — consolidated by ${esc(groupingName(o.levels))}</h2><div class="wrap"><table><thead><tr><th class="num">Sl</th>` +
      '<th>Service No</th><th>Short Text</th><th>Unit</th><th class="num">Qty</th><th class="num">Price</th><th class="num">Amount</th></tr></thead><tbody>';
    for (const r of reportRows(o.levels, o.hideZero, o.detail)) {
      if (r.type === 'group') body += `<tr class="g g${r.depth}"><td colspan="7">${esc(r.label)}: ${esc(r.name)}</td></tr>`;
      else if (r.type === 'item') {
        const t = itemText(r.it);
        body += `<tr><td class="num">${r.sl}</td><td>${esc(r.it.code)}</td><td>${esc(t.short)}</td><td>${esc(t.unit)}</td>` +
          `<td class="num">${esc(t.qty)}</td><td class="num">${esc(t.price)}</td><td class="num">${esc(t.amount)}</td></tr>`;
      } else if (r.type === 'detail') {
        body += `<tr class="d"><td></td><td class="num">#${r.ln.n}</td><td colspan="2">${esc(r.ln.desc)}</td>` +
          `<td class="num">${esc(fmtQty(r.ln.qty, r.it.uf))}</td><td></td><td></td></tr>`;
      } else if (r.type === 'subtotal') {
        body += `<tr class="st"><td colspan="6" class="num">Total ${esc(r.name)}</td><td class="num">${fmtMoney(r.amount)}</td></tr>`;
      } else {
        body += `<tr class="gt"><td colspan="6" class="num">Grand total</td><td class="num">${fmtMoney(r.amount)}</td></tr>`;
      }
    }
    body += '</tbody></table></div>';
  }
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="${esc(APP_ID)}">
<title>${esc(title)}</title>
<style>
body { font: 12px/1.35 Arial, Helvetica, sans-serif; color: #111; background: #fff; margin: 16px; }
h1 { font-size: 18px; margin: 0 0 4px; } h2 { font-size: 14px; margin: 22px 0 6px; }
.meta { color: #555; margin: 0 0 8px; }
table { border-collapse: collapse; width: 100%; }
.wrap { overflow-x: auto; }
th, td { border: 1px solid #ccc; padding: 3px 5px; vertical-align: top; text-align: left; }
th { background: #eee; }
.num { text-align: right; white-space: nowrap; }
.sec { font-size: 10px; color: #1f5fbf; }
tr.g td { background: #f0f0f0; font-weight: bold; } tr.g1 td { background: #f8f8f8; padding-left: 18px; }
tr.st td, tfoot td { font-weight: bold; } tr.gt td { font-weight: bold; background: #eee; }
tr.d td { color: #666; font-size: 11px; }
@media print { @page { size: A4 landscape; margin: 10mm; } body { margin: 0; } tr { break-inside: avoid; } }
</style></head><body>
${body}
</body></html>
`;
}

/* ---------- PDF ---------- */
// A4 landscape table document using the standard Helvetica fonts.
// Text is measured with Arial on a canvas, which has Helvetica's widths.
const measureCtx = document.createElement('canvas').getContext('2d');
function textWidth(t, size, bold) {
  measureCtx.font = `${bold ? 'bold ' : ''}${size}px Arial, Helvetica, "Liberation Sans", sans-serif`;
  return measureCtx.measureText(t).width;
}
function wrapText(t, width, size, bold) {
  const out = [];
  for (const para of String(t ?? '').split('\n')) {
    let line = '';
    for (const word of para.split(/\s+/).filter(Boolean)) {
      const tryLine = line ? line + ' ' + word : word;
      if (textWidth(tryLine, size, bold) <= width) { line = tryLine; continue; }
      if (line) out.push(line);
      line = word;
      while (textWidth(line, size, bold) > width && line.length > 1) { // break over-long words
        let k = line.length - 1;
        while (k > 1 && textWidth(line.slice(0, k), size, bold) > width) k--;
        out.push(line.slice(0, k)); line = line.slice(k);
      }
    }
    out.push(line);
  }
  return out.length ? out : [''];
}
// WinAnsi bytes for the standard fonts; anything else becomes "?"
const WIN_ANSI = { '€': 0x80, '‚': 0x82, '„': 0x84, '…': 0x85, '‹': 0x8B, '‘': 0x91, '’': 0x92, '“': 0x93, '”': 0x94,
  '•': 0x95, '–': 0x96, '—': 0x97, '™': 0x99, '›': 0x9B, '₹': null };
function pdfStr(t) {
  let out = '';
  for (const ch of String(t)) {
    let code = ch in WIN_ANSI ? WIN_ANSI[ch] : ch.codePointAt(0);
    if (ch === '₹') { out += 'Rs.'; continue; }
    if (code == null || code > 255) code = 63;
    if (code === 40 || code === 41 || code === 92) out += '\\' + String.fromCharCode(code);
    else if (code < 32 || code > 126) out += '\\' + code.toString(8).padStart(3, '0');
    else out += String.fromCharCode(code);
  }
  return out;
}

function exportPdf(o) {
  const W = 842, H = 595, M = 28, BOTTOM = M + 16;
  const pages = [];
  let ops, y;
  const fmt = n => (Math.round(n * 100) / 100).toString();
  const text = (s, x, yy, size, bold, gray) =>
    ops.push(`${gray ? '0.4 g ' : ''}BT /${bold ? 'F2' : 'F1'} ${fmt(size)} Tf ${fmt(x)} ${fmt(yy)} Td (${pdfStr(s)}) Tj ET${gray ? ' 0 g' : ''}`);
  const rect = (x, yy, w, h, g) => ops.push(`${g} g ${fmt(x)} ${fmt(yy)} ${fmt(w)} ${fmt(h)} re f 0 g`);
  const hline = (x1, x2, yy, wgt = 0.3) => ops.push(`0.7 G ${wgt} w ${fmt(x1)} ${fmt(yy)} m ${fmt(x2)} ${fmt(yy)} l S`);
  function newPage() { ops = []; pages.push(ops); y = H - M; }

  // cols: [{h, w, align}] widths in points summing to the page width
  function table(heading, cols, rows, size) {
    const lh = size * 1.22, pad = 2.5;
    const xs = []; let x = M;
    for (const c of cols) { xs.push(x); x += c.w; }
    const right = x;
    function drawHeader() {
      const lines = cols.map(c => wrapText(c.h, c.w - 2 * pad, size, true));
      const h = Math.max(...lines.map(l => l.length)) * lh + 2 * pad;
      rect(M, y - h, right - M, h, 0.88);
      lines.forEach((ls, i) => ls.forEach((t, k) => {
        const tw = textWidth(t, size, true);
        const tx = cols[i].align === 'r' ? xs[i] + cols[i].w - pad - tw : xs[i] + pad;
        text(t, tx, y - pad - size * 0.85 - k * lh, size, true);
      }));
      y -= h;
    }
    function ensure(h) {
      if (y - h < BOTTOM) { newPage(); text(heading + ' (continued)', M, y - 10, 9, true); y -= 16; drawHeader(); }
    }
    if (y - 60 < BOTTOM) newPage();
    text(heading, M, y - 11, 11, true); y -= 18;
    drawHeader();
    for (const r of rows) {
      const fs = r.small ? size - 0.8 : size;
      if (r.span != null) { // one cell across the row (group heading / total label)
        const spanW = (r.last != null ? xs[cols.length - 1] : right) - M;
        const lines = wrapText(r.span, spanW - 2 * pad - (r.indent || 0), fs, true);
        const h = lines.length * lh + 2 * pad;
        ensure(h);
        if (r.fill) rect(M, y - h, right - M, h, r.fill);
        lines.forEach((t, k) => {
          const tw = textWidth(t, fs, true);
          const tx = r.align === 'r' ? M + spanW - pad - tw : M + pad + (r.indent || 0);
          text(t, tx, y - pad - fs * 0.85 - k * lh, fs, true);
        });
        if (r.last != null) {
          const tw = textWidth(r.last, fs, true);
          text(r.last, right - pad - tw, y - pad - fs * 0.85, fs, true);
        }
        y -= h;
        hline(M, right, y, r.rule ? 0.8 : 0.3);
        continue;
      }
      const b = !!r.bold;
      const lines = r.cells.map((t, i) => wrapText(t, cols[i].w - 2 * pad, fs, b));
      const h = Math.max(...lines.map(l => l.length)) * lh + 2 * pad;
      ensure(h);
      lines.forEach((ls, i) => ls.forEach((t, k) => {
        const tw = textWidth(t, fs, b);
        const tx = cols[i].align === 'r' ? xs[i] + cols[i].w - pad - tw : xs[i] + pad;
        text(t, tx, y - pad - fs * 0.85 - k * lh, fs, b, r.small);
      }));
      y -= h;
      if (!r.small) hline(M, right, y, r.rule ? 0.8 : 0.3);
    }
    y -= 14;
  }

  newPage();
  text(project.name || 'BOQ', M, y - 14, 15, true);
  text(exportMeta().join('   ·   '), M, y - 29, 8, false, true);
  y -= 42;

  const usable = W - 2 * M;
  if (o.sheet) {
    const spec = [['#', 22, 'r'], ['Service No', 44], ['Short Text', 118], ['Description', 118], ['No', 34, 'r'], ['L', 38, 'r'],
      ['B', 34, 'r'], ['H/D', 44, 'r'], ['Qty', 48, 'r'], ['Unit', 26], ['Price', 56, 'r'], ['Amount', 64, 'r'], ['PO Item', 54], ['Asset', 0]];
    const used = spec.reduce((t, c) => t + c[1], 0);
    const cols = spec.map(([h, w, a]) => ({ h, w: w || usable - used, align: a }));
    const rows = sheetRows().map(r => ({ cells: [String(r.n), r.code, r.short, r.desc, r.dims[0], r.dims[1], r.dims[2],
      r.dims[3] + (r.hdSection ? '\n' + r.hdSection : ''), r.qty, r.unit, r.price, r.amount, r.po, r.asset] }));
    const total = Array(cols.length).fill('');
    total[10] = 'Total'; total[11] = fmtMoney(sheetTotal());
    rows.push({ cells: total, bold: true, rule: true });
    table('Measurement sheet', cols, rows, 7);
  }
  if (o.report) {
    const spec = [['Sl', 26, 'r'], ['Service No', 60], ['Short Text', 0], ['Unit', 40], ['Qty', 80, 'r'], ['Price', 80, 'r'], ['Amount', 90, 'r']];
    const used = spec.reduce((t, c) => t + c[1], 0);
    const cols = spec.map(([h, w, a]) => ({ h, w: w || usable - used, align: a }));
    const rows = [];
    for (const r of reportRows(o.levels, o.hideZero, o.detail)) {
      if (r.type === 'group') rows.push({ span: `${r.label}: ${r.name}`, fill: r.depth ? 0.96 : 0.92, indent: r.depth * 12 });
      else if (r.type === 'item') {
        const t = itemText(r.it);
        rows.push({ cells: [String(r.sl), r.it.code, t.short, t.unit, t.qty, t.price, t.amount] });
      } else if (r.type === 'detail') rows.push({ small: true, cells: ['', '#' + r.ln.n, r.ln.desc, '', fmtQty(r.ln.qty, r.it.uf), '', ''] });
      else if (r.type === 'subtotal') rows.push({ span: `Total ${r.name}`, align: 'r', last: fmtMoney(r.amount), rule: true });
      else rows.push({ span: 'Grand total', align: 'r', last: fmtMoney(r.amount), fill: 0.88, rule: true });
    }
    table(`Report — consolidated by ${groupingName(o.levels).replace(/›/g, '>')}`, cols, rows, 8);
  }

  // assemble: page numbers, objects, xref
  const n = pages.length;
  pages.forEach((p, i) => {
    ops = p;
    text(`${project.name || 'BOQ'}`, M, M - 6, 7, false, true);
    const pg = `Page ${i + 1} of ${n}`;
    text(pg, W - M - textWidth(pg, 7, false), M - 6, 7, false, true);
  });
  const objs = [];
  const add = s => { objs.push(s); return objs.length; };
  const catalog = add(null), pagesObj = add(null);
  const f1 = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');
  const f2 = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');
  const kids = [];
  for (const p of pages) {
    const content = p.join('\n');
    const c = add(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);
    kids.push(add(`<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 ${W} ${H}] /Contents ${c} 0 R ` +
      `/Resources << /Font << /F1 ${f1} 0 R /F2 ${f2} 0 R >> >> >>`));
  }
  objs[catalog - 1] = `<< /Type /Catalog /Pages ${pagesObj} 0 R >>`;
  objs[pagesObj - 1] = `<< /Type /Pages /Kids [${kids.map(k => k + ' 0 R').join(' ')}] /Count ${kids.length} >>`;
  const info = add(`<< /Title (${pdfStr(project.name || 'BOQ')}) /Producer (${pdfStr(APP_ID)}) >>`);
  let out = '%PDF-1.4\n';
  const offsets = objs.map((o2, i) => { const off = out.length; out += `${i + 1} 0 obj\n${o2}\nendobj\n`; return off; });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n` + offsets.map(x => String(x).padStart(10, '0') + ' 00000 n \n').join('');
  out += `trailer\n<< /Size ${objs.length + 1} /Root ${catalog} 0 R /Info ${info} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return new Blob([out], { type: 'application/pdf' });
}

/* ---------- Excel (.xlsx) ---------- */
// Cells: null | number | string | { v, f (formula), s (style), t: 's' for text }
// Styles: 0 normal, 1 bold, 2 #,##0.00, 3 #,##0.000, 4 bold #,##0.00, 5 title,
// 6 header, 7 group row, 8 grey detail, 9 grey detail #,##0.000, 10 general number
const XS = { normal: 0, bold: 1, money: 2, qty3: 3, boldMoney: 4, title: 5, head: 6, group: 7, detail: 8, detailQty: 9, gen: 10 };
const qtyStyle = uf => uf.min === 0 ? XS.gen : uf.dp === 2 ? XS.money : XS.qty3;
const colName = i => { let s = ''; i++; while (i) { const m = (i - 1) % 26; s = String.fromCharCode(65 + m) + s; i = (i - m - 1) / 26; } return s; };
const xmlEsc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
  .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '');

function sheetXml({ cols, rows, merges = [], freeze = 0 }) {
  let x = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
    '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">' +
    '<sheetPr><pageSetUpPr fitToPage="1"/></sheetPr>';
  if (freeze) x += `<sheetViews><sheetView workbookViewId="0"><pane ySplit="${freeze}" topLeftCell="A${freeze + 1}" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>`;
  x += '<cols>' + cols.map((w, i) => `<col min="${i + 1}" max="${i + 1}" width="${w}" customWidth="1"/>`).join('') + '</cols><sheetData>';
  rows.forEach((row, ri) => {
    if (!row) return;
    x += `<row r="${ri + 1}">`;
    row.forEach((cell, ci) => {
      if (cell == null || cell === '') return;
      const c = typeof cell === 'object' ? cell : { v: cell };
      const ref = colName(ci) + (ri + 1), s = c.s ? ` s="${c.s}"` : '';
      if (c.f) x += `<c r="${ref}"${s}><f>${xmlEsc(c.f)}</f>${typeof c.v === 'number' && isFinite(c.v) ? `<v>${c.v}</v>` : ''}</c>`;
      else if (typeof c.v === 'number' && c.t !== 's') x += `<c r="${ref}"${s}><v>${c.v}</v></c>`;
      else x += `<c r="${ref}"${s} t="inlineStr"><is><t xml:space="preserve">${xmlEsc(c.v)}</t></is></c>`;
    });
    x += '</row>';
  });
  x += '</sheetData>';
  if (merges.length) x += `<mergeCells count="${merges.length}">` + merges.map(m => `<mergeCell ref="${m}"/>`).join('') + '</mergeCells>';
  x += '<pageMargins left="0.4" right="0.4" top="0.5" bottom="0.5" header="0.3" footer="0.3"/>' +
    '<pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>';
  return x;
}
const STYLES_XML = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
  '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">' +
  '<numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.000"/></numFmts>' +
  '<fonts count="4"><font><sz val="10"/><name val="Arial"/></font><font><b/><sz val="10"/><name val="Arial"/></font>' +
  '<font><b/><sz val="14"/><name val="Arial"/></font><font><sz val="9"/><color rgb="FF666666"/><name val="Arial"/></font></fonts>' +
  '<fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill>' +
  '<fill><patternFill patternType="solid"><fgColor rgb="FFD9D9D9"/></patternFill></fill>' +
  '<fill><patternFill patternType="solid"><fgColor rgb="FFF2F2F2"/></patternFill></fill></fills>' +
  '<borders count="2"><border/><border><bottom style="thin"><color rgb="FF999999"/></bottom></border></borders>' +
  '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="11">' +
  '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>' +
  '<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/>' +
  '<xf numFmtId="4" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>' +
  '<xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>' +
  '<xf numFmtId="4" fontId="1" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyFont="1"/>' +
  '<xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/>' +
  '<xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf>' +
  '<xf numFmtId="0" fontId="1" fillId="3" borderId="0" xfId="0" applyFont="1" applyFill="1"/>' +
  '<xf numFmtId="0" fontId="3" fillId="0" borderId="0" xfId="0" applyFont="1"/>' +
  '<xf numFmtId="164" fontId="3" fillId="0" borderId="0" xfId="0" applyFont="1" applyNumberFormat="1"/>' +
  '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>' +
  '</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';

function exportXlsx(o) {
  const sheets = [];
  const codeCell = code => /^\d{1,15}$/.test(code || '') ? Number(code) : (code || '');
  const head = [[{ v: project.name || 'BOQ', s: XS.title }], [{ v: exportMeta().join('   ·   '), s: XS.detail }], null];
  if (o.sheet) {
    const rows = [...head];
    rows.push(['#', 'Service No', 'Short Text', 'Description', 'No', 'L', 'B', 'H/D', 'Qty', 'Unit', 'Price', 'Amount', 'PO Item', 'Asset', 'H/D section']
      .map(v => ({ v, s: XS.head })));
    const first = rows.length + 1;
    for (const r of sheetRows()) {
      const R = rows.length + 1, l = r.line, c = r.c;
      const dims = DIMS.map(d => {
        const e = evalExpr(l[d]);
        if (e.error) return { v: l[d], t: 's' };
        if (e.value === null) return null;
        return isPlainNumber(l[d]) ? { v: e.value, s: XS.gen } : { f: excelFormula(e.ast), v: e.value, s: XS.gen };
      });
      const qty = c.err ? { v: '#ERR', t: 's' }
        : { f: `ROUND(PRODUCT(E${R}:H${R}),${c.uf.dp})`, v: c.qty, s: qtyStyle(c.uf) };
      rows.push([r.n, codeCell(r.code), r.short, r.desc, ...dims, qty, r.unit,
        c.sor ? { v: c.price, s: XS.money } : (c.look ? '—' : null),
        c.sor && !c.err ? { f: `ROUND(I${R}*K${R},2)`, v: c.amount, s: XS.money } : null,
        r.po, r.asset, r.hdSection]);
    }
    const last = rows.length;
    rows.push([null, null, null, null, null, null, null, null, null, null, { v: 'Total', s: XS.bold },
      { f: `SUM(L${first}:L${last})`, v: sheetTotal(), s: XS.boldMoney }]);
    sheets.push({ name: 'Measurement', xml: sheetXml({ cols: [5, 11, 34, 34, 8, 8, 8, 9, 11, 6, 11, 13, 12, 18, 14], rows, freeze: 4 }) });
  }
  if (o.report) {
    const rows = [...head, [{ v: `Consolidated by ${groupingName(o.levels)}`, s: XS.bold }]];
    rows.push(['Sl', 'Service No', 'Short Text', 'Unit', 'Qty', 'Price', 'Amount'].map(v => ({ v, s: XS.head })));
    const merges = [];
    for (const r of reportRows(o.levels, o.hideZero, o.detail)) {
      const R = rows.length + 1;
      if (r.type === 'group') {
        rows.push([{ v: `${'    '.repeat(r.depth)}${r.label}: ${r.name}`, s: XS.group }, ...Array(6).fill({ v: '', s: XS.group })]);
        merges.push(`A${R}:G${R}`);
      } else if (r.type === 'item') {
        const it = r.it, t = itemText(it);
        rows.push([r.sl, codeCell(it.code), t.short, t.unit,
          it.err ? '#ERR' : { v: it.qty, s: qtyStyle(it.uf) },
          it.sor ? { v: it.price, s: XS.money } : (it.look ? '—' : null),
          it.sor && !it.err ? { f: `ROUND(E${R}*F${R},2)`, v: it.amount, s: XS.money } : null]);
      } else if (r.type === 'detail') {
        rows.push([null, { v: '#' + r.ln.n, s: XS.detail }, { v: r.ln.desc, s: XS.detail }, null,
          { v: r.ln.qty, s: XS.detailQty }]);
      } else {
        rows.push([null, null, { v: r.type === 'grand' ? 'Grand total' : `Total ${r.name}`, s: XS.bold }, null, null, null,
          { v: r.amount, s: XS.boldMoney }]);
      }
    }
    sheets.push({ name: 'Report', xml: sheetXml({ cols: [5, 11, 48, 7, 12, 12, 15], rows, merges, freeze: 5 }) });
  }
  const files = [
    ['[Content_Types].xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
      '<Default Extension="xml" ContentType="application/xml"/>' +
      '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>' +
      '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>' +
      sheets.map((s, i) => `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('') +
      '</Types>'],
    ['_rels/.rels', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
    ['xl/workbook.xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>' +
      sheets.map((s, i) => `<sheet name="${s.name}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`).join('') +
      '</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>'],
    ['xl/_rels/workbook.xml.rels', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' +
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
      sheets.map((s, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`).join('') +
      `<Relationship Id="rId${sheets.length + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`],
    ['xl/styles.xml', STYLES_XML],
    ...sheets.map((s, i) => [`xl/worksheets/sheet${i + 1}.xml`, s.xml]),
  ];
  return new Blob([zipStore(files)], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

// Minimal ZIP writer (stored, no compression) — all an .xlsx needs
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; }
  return t;
})();
function crc32(b) { let c = 0xFFFFFFFF; for (let i = 0; i < b.length; i++) c = CRC_TABLE[(c ^ b[i]) & 0xFF] ^ (c >>> 8); return (c ^ 0xFFFFFFFF) >>> 0; }
function zipStore(files) {
  const enc = new TextEncoder();
  const entries = files.map(([name, text]) => ({ name: enc.encode(name), data: enc.encode(text) }));
  entries.forEach(e => { e.crc = crc32(e.data); });
  const size = entries.reduce((t, e) => t + 30 + e.name.length + e.data.length + 46 + e.name.length, 22);
  const buf = new Uint8Array(size), dv = new DataView(buf.buffer);
  let p = 0;
  const u16 = v => { dv.setUint16(p, v, true); p += 2; }, u32 = v => { dv.setUint32(p, v, true); p += 4; };
  for (const e of entries) {
    e.offset = p;
    u32(0x04034B50); u16(20); u16(0x0800); u16(0); u16(0); u16(0x21);
    u32(e.crc); u32(e.data.length); u32(e.data.length); u16(e.name.length); u16(0);
    buf.set(e.name, p); p += e.name.length; buf.set(e.data, p); p += e.data.length;
  }
  const cd = p;
  for (const e of entries) {
    u32(0x02014B50); u16(20); u16(20); u16(0x0800); u16(0); u16(0); u16(0x21);
    u32(e.crc); u32(e.data.length); u32(e.data.length); u16(e.name.length); u16(0); u16(0); u16(0); u16(0); u32(0); u32(e.offset);
    buf.set(e.name, p); p += e.name.length;
  }
  const cdSize = p - cd;
  u32(0x06054B50); u16(0); u16(0); u16(entries.length); u16(entries.length); u32(cdSize); u32(cd); u16(0);
  return buf;
}
