#!/usr/bin/env python3
# MBook — Copyright (C) 2026 rupsdbb
# SPDX-License-Identifier: GPL-3.0-or-later
"""Extract the SOR and BIS sheets from a workbook into data/sor.js and data/bis.js.

Usage: python3 tools/extract_data.py "path/to/workbook.xlsm" [--state "Bihar"]

Each State publishes its own SOR. A State column (H) in the SOR sheet tags
each rate; --state tags every rate that has none. Untagged rates apply in
every State.

Needs openpyxl (pip install openpyxl). data/sor.js holds your own rates and is
kept out of git (.gitignore); without it the app falls back to
data/sor.sample.js. The app can also load SOR/BIS from a CSV at runtime.
"""
import datetime
import json
import os
import sys

import openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def iso(v):
    if isinstance(v, datetime.datetime):
        return v.date().isoformat()
    return v or ""


def code_text(v):
    # A code saved as a number may come back as 7006142.0
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    return str(v).strip()


def extract_sor(ws, default_state=""):
    items = []
    for row in ws.iter_rows(min_row=2, max_col=8, values_only=True):
        code, short, rate, unit, vfrom, vto, long_text, state = row
        if code is None:
            continue
        if long_text in ("#N/A", None):
            long_text = ""
        items.append({
            "code": code_text(code),
            "short": (short or "").strip(),
            "rate": float(rate or 0),
            "unit": (unit or "").strip(),
            "from": iso(vfrom),
            "to": iso(vto),
            "long": str(long_text).strip(),
        })
        state = str(state or default_state).strip()
        if state:
            items[-1]["state"] = state
    return items


def extract_bis(ws):
    items = []
    group = ""
    for row in ws.iter_rows(min_row=2, max_col=3, values_only=True):
        name, weight, cat = row
        if cat:
            group = str(cat).strip()
        if name is None or weight is None:
            continue
        items.append({"name": str(name).strip(), "kgm": float(weight), "group": group})
    return items


def write_js(path, var, data, source):
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"// Generated by tools/extract_data.py from {source}\n")
        f.write(f"window.{var} = ")
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")


def main():
    args = sys.argv[1:]
    state = ""
    if "--state" in args:
        i = args.index("--state")
        state = args[i + 1] if i + 1 < len(args) else sys.exit("--state needs a name")
        del args[i:i + 2]
    if len(args) != 1:
        sys.exit(__doc__)
    src = args[0]
    wb = openpyxl.load_workbook(src, data_only=True, read_only=True)
    sor = extract_sor(wb["SOR"], state)
    bis = extract_bis(wb["BIS"])
    name = os.path.basename(src)
    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    write_js(os.path.join(ROOT, "data", "sor.js"), "DEFAULT_SOR",
             {"source": name, "items": sor}, name)
    # BIS weights are standard published data, so they are labelled as such
    # rather than with the workbook's name (bis.js is published; sor.js is not)
    write_js(os.path.join(ROOT, "data", "bis.js"), "DEFAULT_BIS",
             {"source": "BIS steel section tables", "items": bis}, "the BIS handbook tables")
    print(f"SOR: {len(sor)} items, BIS: {len(bis)} sections")


if __name__ == "__main__":
    main()
